### ISSUE TITLE
Grant uPortal Committers privileged access to repository

### ISSUE THREAD

**Issue by ChristianMurphy** [uPortal-contrib/form-builder#26]
> The committers for this project are those for uPortal itself, documented as of this writing in COMMITTERS.md in Jasig/uPortal.

https://github.com/uPortal-contrib/form-builder/blob/master/COMMITTERS.md

Currently access is limited to only @cparaiso and @uPortal-contrib/uportal-steering-committee

**Comment by apetro** [comment]
Done:

![up-committers-as-form-builder-committers](https://user-images.githubusercontent.com/952283/42583890-8e6ba6e4-84f7-11e8-891c-369dfa58df8d.png)

**Comment by ChristianMurphy** [comment]
Thanks @apetro! :bow:
