### ISSUE TITLE
Validation errors continue to display, even after the user corrects them

### ISSUE THREAD

**Issue by drewwills** [uPortal-contrib/form-builder#36]
The form-builder UI is now correctly displaying server-side validation errors.

But I notice now that if I produce a validation error and then correct it, the error still displays (in red) when I re-submit the form.  The submission is a success, and the updated/corrected version is saved, but the user is told that the validation issue is still a problem.

**Comment by ChristianMurphy** [comment]
resolved in 2e99f5e
