### ISSUE TITLE
When validation errors are displayed, the form resets to its initial state, and the user's inputs are lost

### ISSUE THREAD

**Issue by drewwills** [uPortal-contrib/form-builder#37]
I would expect that when the form displays server-side submission errors (e.g. validation issues) the widgets on the form would remain exactly as the user just set them.

Instead, the form is reverting to the state it had when the page first loaded.

**Comment by ChristianMurphy** [comment]
@drewwills What are you running? version 0.2.1 may have a fix.

**Comment by drewwills** [comment]
I am running 0.2.1 -- I had to get past the earlier validation issue even to see this one.
