### ISSUE TITLE
Please update the build script to produce a .map file with the same name as the .js file

### ISSUE THREAD

**Issue by drewwills** [uPortal-contrib/form-builder#38]
The build produces...
  - build/static/js/form-builder.js
  - build/static/js/main.5f6c9cfc.js.map
I don't believe the browser can use the .map file unless it matches in name.

**Comment by ChristianMurphy** [comment]
As long as the form-builder.js includes
```js
//# sourceMappingURL=main.5f6c9cfc.js.map
```

at the end the source map will be picked up.

**Comment by ChristianMurphy** [comment]
ref: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

**Comment by drewwills** [comment]
That bit is there, but it doesn't appear to be working.

**Comment by ChristianMurphy** [comment]
What version and what browser are you running?
I'm testing with version 0.2.2 and I can see the full project structure from the minified file in the developer console.
![selection_016](https://user-images.githubusercontent.com/3107513/43742112-8d2fda8c-9985-11e8-9785-19744d5067fc.png)

**Comment by drewwills** [comment]
Using Chrome.  I only see the transpiled & minified file in the `sources` tab.

**Comment by ChristianMurphy** [comment]
Seeing it in Chrome as well in version 0.2.2.

![selection_017](https://user-images.githubusercontent.com/3107513/43742380-8e6cb1b2-9986-11e8-8153-c14e62d366cb.png)

Are there any errors in the network tab or developer console warning about `main.5f6c9cfc.js.map` being not found?

**Comment by ChristianMurphy** [comment]
Confirmed offline this is working.
Chrome doesn't automatically jump to the source mapped version when it available, which can be confusing.
