### ISSUE TITLE
Check mark displayed after submitting a form is too big

### ISSUE THREAD

**Issue by drewwills** [uPortal-contrib/form-builder#53]
## Description

![icon-too-big](https://user-images.githubusercontent.com/1127174/46701690-6ce1a580-cbd5-11e8-8a6d-d4b28a2eaf58.png)

## Affects Version

1.1.0

**Comment by ChristianMurphy** [comment]
Resolved in version 1.1.2 https://github.com/uPortal-contrib/form-builder/blob/master/CHANGELOG.md#112---2018-10-10
