### ISSUE TITLE
form-builder seems not to load at all on Firefox

### ISSUE THREAD

**Issue by drewwills** [uPortal-contrib/form-builder#54]
## Description

![form-builder-broken-firefox](https://user-images.githubusercontent.com/1127174/46701805-d19d0000-cbd5-11e8-90cc-2a0d0b95c22f.png)

## Affects Version

1.1.0

**Comment by ChristianMurphy** [comment]
Resolved in version 1.1.2 https://github.com/uPortal-contrib/form-builder/blob/master/CHANGELOG.md#112---2018-10-10
